# Stage 1: Backend Application
FROM eclipse-temurin:17-jdk-alpine as backend
VOLUME /tmp
ARG WAR_FILE
COPY ${WAR_FILE} app.war
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.war"]

# Stage 2: MSSQL Database
# FROM mcr.microsoft.com/mssql/server:2022-latest as database
# USER mssql
# ENV ACCEPT_EULA=Y
# ENV SA_PASSWORD=YourPassword123!
# EXPOSE 1433
# CMD ["/opt/mssql/bin/sqlservr"]

FROM backend as backend-image

# FROM database as database-image
